name: Create Production Builds

jobs:
  build_android:
    type: build
    params:
      platform: android
      profile: production

  submit_android:
    type: submit
    params:
      build_id: ${{ needs.build_android.outputs.build_id }}
      profile: production
    needs:
      - build_android

  build_ios:
    type: build
    params:
      platform: ios
      profile: production

  submit_ios:
    type: submit
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
      profile: production
    needs:
      - build_ios

