/**
 * Email Schema
 * 
 * Path: /users/{userId}/emails/{emailId}
 * 
 * Represents email operations for the notification system.
 * Each document tracks one email from planning to delivery.
 */

export interface EmailSchema {
  // Recipient email address
  to: string;
  
  // Email subject
  subject: string;
  
  // Email body in Markdown format (generated by AI)
  // Will be converted to HTML by TypeScript trigger before sending
  body_markdown: string;
  
  // Current state of email operation
  state: 'PLANNED' | 'SENDING' | 'SENT' | 'FAILED';
  
  // When email was successfully sent
  sentAt?: string; // ISO 8601 timestamp
  
  // Error message if sending failed
  lastErrorMessage?: string;
  
  // When this email operation was created
  createdAt: string; // ISO 8601 timestamp
}

/**
 * Default values for new email
 */
export const EmailDefaults: Partial<EmailSchema> = {
  state: 'PLANNED',
};

/**
 * Version tracking
 * Increment this when making breaking schema changes
 * 
 * Version 1: Initial email schema for notification system
 * Version 2: Changed body_text to body_markdown (AI generates Markdown, trigger converts to HTML)
 */
export const EMAIL_SCHEMA_VERSION = 2;

